name: CI

on:
  push:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '*/1 * * * *'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build MyProject
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install .
        make -j3
        make install
    - name: Check build
      run: |
        ctest -R .
    - name: Package
      run: |
        make package